In [1]:
# 오류 메시지 무시
import warnings
warnings.filterwarnings('ignore')

In [2]:
#데이터 불러오기
import pandas as pd
df_PCOS=pd.read_excel("../Data/PCOS_data_without_infertility.xlsx",sheet_name="Full_new")
df_PCOS.head(3)

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm),Unnamed: 44
0,1,1,0,28,44.6,152.0,19.300000,15,78,22,...,1.0,0,110,80,3,3,18.0,18.0,8.5,NaN
1,2,2,0,36,65.0,161.5,24.921163,15,74,20,...,0.0,0,120,70,3,5,15.0,14.0,3.7,NaN
2,3,3,1,33,68.8,165.0,25.270891,11,72,18,...,1.0,0,120,80,13,15,18.0,20.0,10.0,NaN

In [3]:
df_PCOS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 45 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sl. No                  541 non-null    int64
 1   Patient File No.        541 non-null    int64
 2   PCOS (Y/N)              541 non-null    int64
 3    Age (yrs)              541 non-null    int64
 4   Weight (Kg)             541 non-null    float64
 5   Height(Cm)              541 non-null    float64
 6   BMI                     541 non-null    float64
 7   Blood Group             541 non-null    int64
 8   Pulse rate(bpm)         541 non-null    int64
 9   RR (breaths/min)        541 non-null    int64
 10  Hb(g/dl)                541 non-null    float64
 11  Cycle(R/I)              541 non-null    int64
 12  Cycle length(days)      541 non-null    int64
 13  Marraige Status (Yrs)   540 non-null    float64
 14  Pregnant(Y/N)           541 non-null    int64
 15  No. of aborptions       541 non-null    int64
 16    I   beta-HCG(mIU/mL)  541 non-null    float64
 17  II    beta-HCG(mIU/mL)  541 non-null    object
 18  FSH(mIU/mL)             541 non-null    float64
 19  LH(mIU/mL)              541 non-null    float64
 20  FSH/LH                  541 non-null    float64
 21  Hip(inch)               541 non-null    int64
 22  Waist(inch)             541 non-null    int64
 23  Waist:Hip Ratio         541 non-null    float64
 24  TSH (mIU/L)             541 non-null    float64
 25  AMH(ng/mL)              541 non-null    object
 26  PRL(ng/mL)              541 non-null    float64
 27  Vit D3 (ng/mL)          541 non-null    float64
 28  PRG(ng/mL)              541 non-null    float64
 29  RBS(mg/dl)              541 non-null    float64
 30  Weight gain(Y/N)        541 non-null    int64
 31  hair growth(Y/N)        541 non-null    int64
 32  Skin darkening (Y/N)    541 non-null    int64
 33  Hair loss(Y/N)          541 non-null    int64
 34  Pimples(Y/N)            541 non-null    int64
 35  Fast food (Y/N)         540 non-null    float64
 36  Reg.Exercise(Y/N)       541 non-null    int64
 37  BP _Systolic (mmHg)     541 non-null    int64
 38  BP _Diastolic (mmHg)    541 non-null    int64
 39  Follicle No. (L)        541 non-null    int64
 40  Follicle No. (R)        541 non-null    int64
 41  Avg. F size (L) (mm)    541 non-null    float64
 42  Avg. F size (R) (mm)    541 non-null    float64
 43  Endometrium (mm)        541 non-null    float64
 44  Unnamed: 44             2 non-null      object
dtypes: float64(19), int64(23), object(3)
memory usage: 190.3+ KB

# Feature Column 선택하기
- 사용자가 스스로 입력할 수 있는 Column만 선택

In [4]:
df_PCOS_use = df_PCOS[['PCOS (Y/N)',' Age (yrs)','Weight (Kg)','Height(Cm) ', 'BMI', 'Blood Group', 
            'Pulse rate(bpm) ','Cycle length(days)','Marraige Status (Yrs)','Pregnant(Y/N)',
            'No. of aborptions','Hip(inch)','Waist(inch)','Waist:Hip Ratio','Weight gain(Y/N)','hair growth(Y/N)',
            'Skin darkening (Y/N)', 'Hair loss(Y/N)','Pimples(Y/N)','Fast food (Y/N)','Reg.Exercise(Y/N)','BP _Systolic (mmHg)','BP _Diastolic (mmHg)']]

In [5]:
df_PCOS_use.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PCOS (Y/N)             541 non-null    int64
 1    Age (yrs)             541 non-null    int64
 2   Weight (Kg)            541 non-null    float64
 3   Height(Cm)             541 non-null    float64
 4   BMI                    541 non-null    float64
 5   Blood Group            541 non-null    int64
 6   Pulse rate(bpm)        541 non-null    int64
 7   Cycle length(days)     541 non-null    int64
 8   Marraige Status (Yrs)  540 non-null    float64
 9   Pregnant(Y/N)          541 non-null    int64
 10  No. of aborptions      541 non-null    int64
 11  Hip(inch)              541 non-null    int64
 12  Waist(inch)            541 non-null    int64
 13  Waist:Hip Ratio        541 non-null    float64
 14  Weight gain(Y/N)       541 non-null    int64
 15  hair growth(Y/N)       541 non-null    int64
 16  Skin darkening (Y/N)   541 non-null    int64
 17  Hair loss(Y/N)         541 non-null    int64
 18  Pimples(Y/N)           541 non-null    int64
 19  Fast food (Y/N)        540 non-null    float64
 20  Reg.Exercise(Y/N)      541 non-null    int64
 21  BP _Systolic (mmHg)    541 non-null    int64
 22  BP _Diastolic (mmHg)   541 non-null    int64
dtypes: float64(6), int64(17)
memory usage: 97.3 KB

## 칼럼 설명
- PCOS : 다낭성 난소 증후군(발병 여부)
- Age: 나이
- Weight : 몸무게(kg)
- Height : 키(cm)
- BMI : 체질량 지수
- Blood Group : 혈액형
- Pulse_rate : 심박수
- Cycle_length : 생리주기 기간
- Marry_status : 결혼 연차
- Pregnant : 임신여부
- Aborptions :낙태유무
- Hip : 힙 크기
- Waist : 허리 사이즈
- WHRatio : 허리와 엉덩이  비율
- Weight_gain : 체중 증가유무
- Hair_growth : 다모증 유무
- Skin_darkening : 흑색 극세포증 유무
- Hair_loss : 탈모 유무
- Pimples : 여드름 유무
- Fast_food : 패스트 푸드 섭취 유무확인
- Reg_exercise : 운동여부
- BP_systolic : 수축기  혈압
- BP_diastolic : 확장기  혈압

In [6]:
#na값 확인하기
df_PCOS_use.isna().sum()

PCOS (Y/N)               0
 Age (yrs)               0
Weight (Kg)              0
Height(Cm)               0
BMI                      0
Blood Group              0
Pulse rate(bpm)          0
Cycle length(days)       0
Marraige Status (Yrs)    1
Pregnant(Y/N)            0
No. of aborptions        0
Hip(inch)                0
Waist(inch)              0
Waist:Hip Ratio          0
Weight gain(Y/N)         0
hair growth(Y/N)         0
Skin darkening (Y/N)     0
Hair loss(Y/N)           0
Pimples(Y/N)             0
Fast food (Y/N)          1
Reg.Exercise(Y/N)        0
BP _Systolic (mmHg)      0
BP _Diastolic (mmHg)     0
dtype: int64

> df_PCOS_use에는 na값이 2개 있는 것을 알 수 있다.

In [7]:
#데이터 타입을 전부 float로 바꿔주기
df_PCOS_use = df_PCOS_use.astype('float')
df_PCOS_use.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PCOS (Y/N)             541 non-null    float64
 1    Age (yrs)             541 non-null    float64
 2   Weight (Kg)            541 non-null    float64
 3   Height(Cm)             541 non-null    float64
 4   BMI                    541 non-null    float64
 5   Blood Group            541 non-null    float64
 6   Pulse rate(bpm)        541 non-null    float64
 7   Cycle length(days)     541 non-null    float64
 8   Marraige Status (Yrs)  540 non-null    float64
 9   Pregnant(Y/N)          541 non-null    float64
 10  No. of aborptions      541 non-null    float64
 11  Hip(inch)              541 non-null    float64
 12  Waist(inch)            541 non-null    float64
 13  Waist:Hip Ratio        541 non-null    float64
 14  Weight gain(Y/N)       541 non-null    float64
 15  hair growth(Y/N)       541 non-null    float64
 16  Skin darkening (Y/N)   541 non-null    float64
 17  Hair loss(Y/N)         541 non-null    float64
 18  Pimples(Y/N)           541 non-null    float64
 19  Fast food (Y/N)        540 non-null    float64
 20  Reg.Exercise(Y/N)      541 non-null    float64
 21  BP _Systolic (mmHg)    541 non-null    float64
 22  BP _Diastolic (mmHg)   541 non-null    float64
dtypes: float64(23)
memory usage: 97.3 KB

In [8]:
# na값을 중앙값으로 채워넣기
for x in df_PCOS_use.columns[df_PCOS_use.isna().any()].tolist():
    df_PCOS_use[x] = df_PCOS_use[x].fillna(df_PCOS_use[x].median())

In [9]:
#na값 다시 확인
df_PCOS_use.isna().any()

PCOS (Y/N)               False
 Age (yrs)               False
Weight (Kg)              False
Height(Cm)               False
BMI                      False
Blood Group              False
Pulse rate(bpm)          False
Cycle length(days)       False
Marraige Status (Yrs)    False
Pregnant(Y/N)            False
No. of aborptions        False
Hip(inch)                False
Waist(inch)              False
Waist:Hip Ratio          False
Weight gain(Y/N)         False
hair growth(Y/N)         False
Skin darkening (Y/N)     False
Hair loss(Y/N)           False
Pimples(Y/N)             False
Fast food (Y/N)          False
Reg.Exercise(Y/N)        False
BP _Systolic (mmHg)      False
BP _Diastolic (mmHg)     False
dtype: bool

In [10]:
# 칼럼 명 변경
df_PCOS_use.columns = ['PCOS', 'Age', 'Weight', 'Height', 'BMI',
       'Blood Type', 'Pulse rate', 'Cycle length',
       'Marraige Status', 'Pregnant', 'aborptions',
       'Hip', 'Waist', 'Waist:Hip Ratio', 'Weight gain',
       'hair growth', 'Skin darkening', 'Hair loss',
       'Pimples', 'Fast food', 'Reg.Exercise',
       'BP_Systolic', 'BP_Diastolic']
df_PCOS_use.head()

,PCOS,Age,Weight,Height,BMI,Blood Type,Pulse rate,Cycle length,Marraige Status,Pregnant,...,Waist:Hip Ratio,Weight gain,hair growth,Skin darkening,Hair loss,Pimples,Fast food,Reg.Exercise,BP_Systolic,BP_Diastolic
0,0.0,28.0,44.6,152.0,19.300000,15.0,78.0,5.0,7.0,0.0,...,0.833333,0.0,0.0,0.0,0.0,0.0,1.0,0.0,110.0,80.0
1,0.0,36.0,65.0,161.5,24.921163,15.0,74.0,5.0,11.0,1.0,...,0.842105,0.0,0.0,0.0,0.0,0.0,0.0,0.0,120.0,70.0
2,1.0,33.0,68.8,165.0,25.270891,11.0,72.0,5.0,10.0,1.0,...,0.900000,0.0,0.0,0.0,1.0,1.0,1.0,0.0,120.0,80.0
3,0.0,37.0,65.0,148.0,29.674945,13.0,72.0,5.0,4.0,0.0,...,0.857143,0.0,0.0,0.0,0.0,0.0,0.0,0.0,120.0,70.0
4,0.0,25.0,52.0,161.0,20.060954,11.0,72.0,5.0,1.0,1.0,...,0.810811,0.0,0.0,0.0,1.0,0.0,0.0,0.0,120.0,80.0

In [11]:
#데이터 저장하기
df_PCOS_use.to_csv('../Data/pcos_colums_organize.csv', index=False)