In [63]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [64]:
final_df=pd.read_csv('../Data/pcos_final2.csv')
final_df.tail()

,Unnamed: 0,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),Cycle length(days),Marraige Status (Yrs),...,Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),BMI_a,BMI_b,BMI_c,hypo_s,normal_s,pre_hyper_s,hyper_s
536,536,0.0,35.0,50.0,164.592,18.5,17.0,72.0,5.0,8.0,...,0.0,110.0,70.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
537,537,0.0,30.0,63.2,158.000,25.3,15.0,72.0,5.0,4.0,...,0.0,110.0,70.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
538,538,0.0,36.0,54.0,152.000,23.4,13.0,74.0,6.0,8.0,...,0.0,110.0,80.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
539,539,0.0,27.0,50.0,150.000,22.2,15.0,74.0,2.0,2.0,...,0.0,110.0,70.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
540,540,1.0,23.0,82.0,165.000,30.1,13.0,80.0,7.0,2.0,...,0.0,120.0,70.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [65]:
final_df = final_df.iloc[:,1:]

In [66]:
# PCOS ture false 값 추출.
y=final_df.iloc[:,0]
y

0      0.0
1      0.0
2      1.0
3      0.0
4      0.0
      ...
536    0.0
537    0.0
538    0.0
539    0.0
540    1.0
Name: PCOS (Y/N), Length: 541, dtype: float64

In [67]:
y.value_counts()

0.0    364
1.0    177
Name: PCOS (Y/N), dtype: int64

In [68]:
# x값 만들어주기
x=final_df.iloc[:,1:]
x.isnull().sum()

 Age (yrs)               0
Weight (Kg)              0
Height(Cm)               0
BMI                      0
Blood Group              0
Pulse rate(bpm)          0
Cycle length(days)       0
Marraige Status (Yrs)    0
Pregnant(Y/N)            0
No. of aborptions        0
Hip(inch)                0
Waist(inch)              0
Waist:Hip Ratio          0
Weight gain(Y/N)         0
hair growth(Y/N)         0
Skin darkening (Y/N)     0
Hair loss(Y/N)           0
Pimples(Y/N)             0
Fast food (Y/N)          0
Reg.Exercise(Y/N)        0
BP _Systolic (mmHg)      0
BP _Diastolic (mmHg)     0
BMI_a                    0
BMI_b                    0
BMI_c                    0
hypo_s                   0
normal_s                 0
pre_hyper_s              0
hyper_s                  0
dtype: int64

In [69]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(x, y, test_size = 0.20, random_state = 42)

In [70]:
y

0      0.0
1      0.0
2      1.0
3      0.0
4      0.0
      ...
536    0.0
537    0.0
538    0.0
539    0.0
540    1.0
Name: PCOS (Y/N), Length: 541, dtype: float64

In [71]:
# feature column 개수 
len(x.columns)

29

In [72]:
x.columns

Index([' Age (yrs)', 'Weight (Kg)', 'Height(Cm) ', 'BMI', 'Blood Group',
       'Pulse rate(bpm) ', 'Cycle length(days)', 'Marraige Status (Yrs)',
       'Pregnant(Y/N)', 'No. of aborptions', 'Hip(inch)', 'Waist(inch)',
       'Waist:Hip Ratio', 'Weight gain(Y/N)', 'hair growth(Y/N)',
       'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)',
       'Fast food (Y/N)', 'Reg.Exercise(Y/N)', 'BP _Systolic (mmHg)',
       'BP _Diastolic (mmHg)', 'BMI_a', 'BMI_b', 'BMI_c', 'hypo_s', 'normal_s',
       'pre_hyper_s', 'hyper_s'],
      dtype='object')

In [73]:
# 정규화
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)

train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [74]:
# Feature를 제곱한 column을 생성하여 기존의 Column에 붙인다.
train_poly = np.column_stack((train_input ** 2, train_input))       # ** 두배 
test_poly = np.column_stack((test_input ** 2, test_input))

In [75]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_poly)

train_poly_scaled= ss.transform(train_poly)
test_poly_scaled = ss.transform(test_poly)

In [76]:
print(train_poly_scaled.shape, test_poly_scaled.shape)

(432, 58) (109, 58)

In [77]:
# 로지스틱 회귀 모델
from sklearn.linear_model import LogisticRegression
# C : Cost function - 높으면 약하게 규제, 낮으면 강하게 규제
lr = LogisticRegression()
lr.fit(train_poly_scaled, train_target)

print("Train Score : ", lr.score(train_poly_scaled, train_target))
print("Test Score : ", lr.score(test_poly_scaled, test_target))

Train Score :  0.8680555555555556
Test Score :  0.8623853211009175

### 예측 답안지 확인

In [78]:

ab2 = lr.predict(test_poly_scaled)
ab = lr.predict_proba(test_poly_scaled)
ab1 = round(ab[0][1] * 100, 2)

In [79]:
comparision = pd.DataFrame(
    {
        '예측값': ab2,
        '정답': test_target
    }
)

#pd.set_option('display.max_rows', None)    # 데이터프레임 컬럼 
comparision

     예측값   정답
229  0.0  0.0
73   0.0  0.0
352  1.0  1.0
86   0.0  0.0
470  0.0  1.0
..   ...  ...
148  1.0  1.0
46   1.0  1.0
93   0.0  0.0
407  0.0  0.0
182  0.0  0.0

[109 rows x 2 columns]

## 사용자 입력 후 예측 결과 확인

In [105]:
# 1, 20: 79%
user_input3 = [[32.0, 80.0, 153.0, 23.49, 17.0, 80.0, 5.0, 18.0, 1.0, 2.0, 38.0, 34.0, 0.89, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 120, 70, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0]]

# 1, 21: 78%
# user_input = [[28.0, 75.0, 165.0, 27.54820937, 15.0, 72.0, 5.0, 2.5, 1.0, 0.0, 45.0, 41.0, 0.9111111111, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 110.0, 70.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0]]

# 1,  0.09 : 99%
# user_input = [[28, 200, 152.0, 19.3, 15.0, 78.0, 5.0, 7.0, 0.0, 0.0, 36.0, 30.0, 0.833, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 110, 80, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0]]

# 0, 56%:43%
# user_input = [[28.0, 74.3, 154.0, 31.32906055, 13.0, 72.0, 5.0, 6.0, 0.0, 3.0, 38.0, 36.0, 0.9473684211, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 110.0, 80.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0]]


# 유저 입력 값 데이터프레임 만들기
user_input1 = pd.DataFrame(user_input3)
# 유저 입력 값 poly 만들기(차원확대)
user_input_poly = np.column_stack((user_input1 ** 2, user_input1))       # ** 두배 
# 유저 입력 값 scaled 만들기
user_poly_scaled= ss.transform(user_input_poly)


# lr.classes_
# 사용된 다중 공식 확인
# print(lr.coef_, lr.intercept_)    # intercept는 마지막에 나오는 배열 match lr.classes_  

# 확률분포검증
# decisions = lr.decision_function(test_poly_scaled)
# np.round(decisions, decimals=2)


ab2 = lr.predict(user_poly_scaled)
ab = lr.predict_proba(user_poly_scaled)
ab1 = round(ab[0][0] * 100, 2)

In [106]:
ab2

array([1.])

In [82]:
final_df2=pd.read_csv('../Data/pcos_pure.csv')
final_df2.tail()

,Unnamed: 0,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),Cycle length(days),Marraige Status (Yrs),...,Skin darkening (Y/N),Hair loss(Y/N),Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),BMI_catg,Systolic_cond,Diastolic_cond
536,536,0.0,35.0,50.0,164.592,18.5,17.0,72.0,5.0,8.0,...,0.0,0.0,0.0,0.0,0.0,110.0,70.0,B,normal,normal
537,537,0.0,30.0,63.2,158.000,25.3,15.0,72.0,5.0,4.0,...,0.0,0.0,0.0,0.0,0.0,110.0,70.0,B,normal,normal
538,538,0.0,36.0,54.0,152.000,23.4,13.0,74.0,6.0,8.0,...,0.0,0.0,0.0,0.0,0.0,110.0,80.0,B,normal,normal
539,539,0.0,27.0,50.0,150.000,22.2,15.0,74.0,2.0,2.0,...,0.0,0.0,1.0,0.0,0.0,110.0,70.0,B,normal,normal
540,540,1.0,23.0,82.0,165.000,30.1,13.0,80.0,7.0,2.0,...,1.0,1.0,1.0,1.0,0.0,120.0,70.0,C,normal,normal

In [83]:
final_df2 = final_df2.iloc[:,1:24]
final_df2

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),Cycle length(days),Marraige Status (Yrs),Pregnant(Y/N),...,Waist:Hip Ratio,Weight gain(Y/N),hair growth(Y/N),Skin darkening (Y/N),Hair loss(Y/N),Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg)
0,0.0,28.0,44.6,152.000,19.300000,15.0,78.0,5.0,7.0,0.0,...,0.833333,0.0,0.0,0.0,0.0,0.0,1.0,0.0,110.0,80.0
1,0.0,36.0,65.0,161.500,24.921163,15.0,74.0,5.0,11.0,1.0,...,0.842105,0.0,0.0,0.0,0.0,0.0,0.0,0.0,120.0,70.0
2,1.0,33.0,68.8,165.000,25.270891,11.0,72.0,5.0,10.0,1.0,...,0.900000,0.0,0.0,0.0,1.0,1.0,1.0,0.0,120.0,80.0
3,0.0,37.0,65.0,148.000,29.674945,13.0,72.0,5.0,4.0,0.0,...,0.857143,0.0,0.0,0.0,0.0,0.0,0.0,0.0,120.0,70.0
4,0.0,25.0,52.0,161.000,20.060954,11.0,72.0,5.0,1.0,1.0,...,0.810811,0.0,0.0,0.0,1.0,0.0,0.0,0.0,120.0,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536,0.0,35.0,50.0,164.592,18.500000,17.0,72.0,5.0,8.0,0.0,...,0.928571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,110.0,70.0
537,0.0,30.0,63.2,158.000,25.300000,15.0,72.0,5.0,4.0,1.0,...,0.941176,1.0,0.0,0.0,0.0,0.0,0.0,0.0,110.0,70.0
538,0.0,36.0,54.0,152.000,23.400000,13.0,74.0,6.0,8.0,0.0,...,0.933333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,110.0,80.0
539,0.0,27.0,50.0,150.000,22.200000,15.0,74.0,2.0,2.0,0.0,...,0.928571,0.0,0.0,0.0,0.0,1.0,0.0,0.0,110.0,70.0
540,1.0,23.0,82.0,165.000,30.100000,13.0,80.0,7.0,2.0,0.0,...,0.958333,1.0,1.0,1.0,1.0,1.0,1.0,0.0,120.0,70.0

- 컬럼 변경

In [84]:
cols = ['PCOS', 'Age', 'Weight', 'Height', 'BMI', 'Blood_type', 'Pulse_rate', 'Cycle_length', 'Marriage_status', 'Pregnant', 'Abortions', 'Hip', 'Waist', 'HWRatio', 'Weight_gain', 'Hair_growth', 'Skin_darkening', 'Hair_loss', 'Pimples', 'Fast_food', 'Reg_exercise', 'BP_systolic', 'BP_diastolic']

In [85]:
final_df2.columns = cols

In [86]:
final_df2.head()

,PCOS,Age,Weight,Height,BMI,Blood_type,Pulse_rate,Cycle_length,Marriage_status,Pregnant,...,HWRatio,Weight_gain,Hair_growth,Skin_darkening,Hair_loss,Pimples,Fast_food,Reg_exercise,BP_systolic,BP_diastolic
0,0.0,28.0,44.6,152.0,19.300000,15.0,78.0,5.0,7.0,0.0,...,0.833333,0.0,0.0,0.0,0.0,0.0,1.0,0.0,110.0,80.0
1,0.0,36.0,65.0,161.5,24.921163,15.0,74.0,5.0,11.0,1.0,...,0.842105,0.0,0.0,0.0,0.0,0.0,0.0,0.0,120.0,70.0
2,1.0,33.0,68.8,165.0,25.270891,11.0,72.0,5.0,10.0,1.0,...,0.900000,0.0,0.0,0.0,1.0,1.0,1.0,0.0,120.0,80.0
3,0.0,37.0,65.0,148.0,29.674945,13.0,72.0,5.0,4.0,0.0,...,0.857143,0.0,0.0,0.0,0.0,0.0,0.0,0.0,120.0,70.0
4,0.0,25.0,52.0,161.0,20.060954,11.0,72.0,5.0,1.0,1.0,...,0.810811,0.0,0.0,0.0,1.0,0.0,0.0,0.0,120.0,80.0

In [87]:
#BMI 컬럼 삭제 :  사용자가 BMI값을 입력하기는 어려움으로
# final_df2.drop('BMI', axis=1, inplace=True)
# final_df2

In [88]:
# target 컬럼 수 포함, 총 컬럼 수
len(final_df2.columns)

23

In [89]:
# 사용자 배열 인덱스 값 맞는지 확인
user_input = [32.0, 80.0, 153.0, 17.0, 80.0, 5.0, 18.0, 1.0, 2.0, 38.0, 34.0, 0.89, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 120, 70]

weight = user_input[1]
height = user_input[2]
p1 = user_input[19]    # Systole
p2 = user_input[20]    # Diastole

print(weight)
print(height)
print(p1)
print(p2)

80.0
153.0
120
70

## 함수 만들기

In [90]:
# bmi, Systole, Diastole 등급값 user_input에 extend(iterable)함수로 array 마지막에 하나씩(총 3개) 추가
# bmi 계산 후 해당 수치에 따라 등급 나눠주기(A, B, C)
def bmi(weight, height):
        # bmi 계산
        bmi = [(weight/((height/100)**2))]
          
        # extend로 넣어줌 
        return user_input.extend(bmi)


# 혈압 입력값에 따라 등급 숫자 추가
def Systole(p1):
      if p1<110:
        p1_c = [0]
      elif p1>=110 and p1<130:
        p1_c = [1]
      elif p1>=130  and p1<140:
        p1_c = [2]
      else:
        p1_c = [3]
        
      # extend로 넣어줌
      return user_input.extend(p1_c)

def Diastole(p2):
      if p2<60:
        p2_c = [0]
      elif p2>=60 and p2<85:
        p2_c = [1]
      elif p2>=85  and p2<90:
        p2_c = [2]
      else:
        p2_c = [3]
        
      # extend로 넣어줌 
      return user_input.extend(p2_c)

- 함수 임의 실행해보기 (실험용)

In [91]:
# 사용자 입력값 이중 배열로 받기 from 플러터
# user_input = [[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
user_input = [32.0, 80.0, 153.0, 17.0, 80.0, 5.0, 18.0, 1.0, 2.0, 38.0, 34.0, 0.89, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 120, 70]

# 사용자 입력값 중 필요한 데이터 변수에 답고 함수 파라미터에 보내기
weight = user_input[1]
height = user_input[2]
p1 = user_input[19]    # Systole
p2 = user_input[20]    # Diastole


print(weight)
print(height)
print(p1)
print(p2)

80.0
153.0
120
70

In [92]:
# 함수 실행
bmi(weight, height)
Systole(p1)
Diastole(p2)

In [93]:
user_input

[32.0,
 80.0,
 153.0,
 17.0,
 80.0,
 5.0,
 18.0,
 1.0,
 2.0,
 38.0,
 34.0,
 0.89,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 120,
 70,
 34.17488999957281,
 1,
 1]

In [94]:
# 추가된 배열 index 위치 확인
print(user_input[21])
print(user_input[22])
print(user_input[23])

34.17488999957281
1
1

### one-hot encoding

In [95]:
# one-hot encoding (혈압 및 BMI)

def BMIResult(bmi):

  x = user_input[21]
  BMIReturn = [0.0,0.0,0.0]
  
  if x<18:
    BMIReturn[0] = 1.0
  elif x>=18 and x<26:
    BMIReturn[1] = 1.0
  else:
    BMIReturn[2] = 1.0

  return user_input.extend(BMIReturn)



def bloodPressure(systole, diastole):

# 배열에 넣고 insert로 iterate(원소) 값만 넣어주기
  bloodreturn = [0.0,0.0,0.0,0.0]

# user_input 값 중 해당 배열 데이터만 가져와서 one-hot encoding 만들기
  sys = user_input[22]
  dia = user_input[23]

  if sys == 0 | dia == 0:
    bloodreturn[0] = 1.0
  elif sys == dia:
    bloodreturn[sys] = 1.0
  else:
    if sys > dia:
      bloodreturn[sys] = 1.0
    else:
      bloodreturn[dia] = 1.0

  return user_input.extend(bloodreturn)

def removes():
  del user_input[21]
  del user_input[22]
  del user_input[23]
  return user_input
#   del var[1]
# var

- one-hot 테스트용

In [96]:
print(user_input[21])
print(user_input[22])
print(user_input[23])

bmi = user_input[21]
systole = user_input[22]
diastole = user_input[23]

34.17488999957281
1
1

In [97]:
BMIResult(bmi)
bloodPressure(systole, diastole)

In [98]:
removes()

[32.0,
 80.0,
 153.0,
 17.0,
 80.0,
 5.0,
 18.0,
 1.0,
 2.0,
 38.0,
 34.0,
 0.89,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 120,
 70,
 1,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0]

In [99]:
len(user_input)

28

In [100]:
user_input

[32.0,
 80.0,
 153.0,
 17.0,
 80.0,
 5.0,
 18.0,
 1.0,
 2.0,
 38.0,
 34.0,
 0.89,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 120,
 70,
 1,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0]

- user_input 배열 차원확대 및 스케일 만들고 예측하는 함수

In [101]:
def predict(user_input):
    
    #유저 입력 값 데이터프레임 만들기
    user_input1 = pd.DataFrame([user_input])
    # 유저 입력 값 poly 만들기(차원확대)
    user_input_poly = np.column_stack((user_input1 ** 2, user_input1))       # ** 두배 
    # 유저 입력 값 scaled 만들기
    user_poly_scaled= ss.transform(user_input_poly)

    # ab = lr.predict_proba(user_poly_scaled)
    # ab1 = round(ab[0][0] * 100, 2)
    

    return ab2
ab2 = lr.predict(user_poly_scaled)

In [102]:
def predict_prob(user_input):
    
    #유저 입력 값 데이터프레임 만들기
    user_input1 = pd.DataFrame([user_input])
    # 유저 입력 값 poly 만들기(차원확대)
    user_input_poly = np.column_stack((user_input1 ** 2, user_input1))       # ** 두배 
    # 유저 입력 값 scaled 만들기
    user_poly_scaled= ss.transform(user_input_poly)

    ab2 = lr.predict(user_poly_scaled)
    # ab = lr.predict_proba(user_poly_scaled)
    # ab1 = round(ab[0][0] * 100, 2)
    

    return ab2

In [103]:
ab1

20.62

In [104]:
ab2

array([1.])

In [108]:
print(len(user_input3[0]))
print(len(user_input))

29
28